# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/person/photo', verbose_name='Фоточка')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус на ЗМШ')),
                ('barcode', models.ImageField(blank=True, upload_to='persons/person/barcode', verbose_name='Штрихкод')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['name'],
            },
        ),
    ]
