# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='persons/person/barcode', verbose_name='Штрихкод'),
        ),
    ]
