# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20170125_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Фоточка'),
        ),
    ]
