# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20170201_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Штрихкод'),
        ),
    ]
