# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_remove_person_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.CharField(default='--', max_length=255, verbose_name='Смешной коммент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.CharField(default=10937, max_length=255, verbose_name='Штрихкод'),
            preserve_default=False,
        ),
    ]
