# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20170201_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Штрихкод'),
        ),
    ]
