# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20170203_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Серёжа Кобяков'),
        ),
    ]
